const User = require('../models/userModel');
const Order = require('../models/orderModel');
const Product=require('../models/productModel')
const PDFDocument = require('pdfkit');
const table = require('pdfkit-table');
const json2xls = require('json2xls');
const ejs = require('ejs');
const fs = require('fs');
const path = require('path');
const util = require('util');
// const pdf = require('html-pdf');
const ExcelJS = require('exceljs');
const moment = require('moment');
const puppeteer = require('puppeteer');
const { order } = require('./orderController');
const { getUserDetailsAndOrders } =require('./adminController')
const flash = require('connect-flash');
const { getTotalRevenue } =require('./adminController')
